In [1]:
import pandas as pd
import sqlite3
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import requests

In [3]:
db_path = os.path.join(os.path.dirname(os.getcwd()), 'data/financials.db')
con = sqlite3.connect(db_path)
data = pd.read_sql("SELECT * FROM economic_indicators", con=con, index_col="id")

In [4]:
data

,date,value,economic_indicator,interval,unit
id,,,,,
0,2024-06-01 00:00:00,5.33,Effective Federal Funds Rate,monthly,percent
1,2024-05-01 00:00:00,5.33,Effective Federal Funds Rate,monthly,percent
2,2024-04-01 00:00:00,5.33,Effective Federal Funds Rate,monthly,percent
3,2024-03-01 00:00:00,5.33,Effective Federal Funds Rate,monthly,percent
4,2024-02-01 00:00:00,5.33,Effective Federal Funds Rate,monthly,percent
...,...,...,...,...,...
9390,1939-05-01 00:00:00,30145.00,Total Nonfarm Payroll,monthly,thousands of persons
9391,1939-04-01 00:00:00,29786.00,Total Nonfarm Payroll,monthly,thousands of persons
9392,1939-03-01 00:00:00,29804.00,Total Nonfarm Payroll,monthly,thousands of persons
9393,1939-02-01 00:00:00,29394.00,Total Nonfarm Payroll,monthly,thousands of persons
9394,1939-01-01 00:00:00,29296.00,Total Nonfarm Payroll,monthly,thousands of persons